"""empty message

Revision ID: 011c991437e3
Revises: None
Create Date: 2016-05-26 20:24:52.209568

"""

# revision identifiers, used by Alembic.
revision = '011c991437e3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
    op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=False)
    op.create_table('sensor',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_id'), 'sensor', ['id'], unique=True)
    op.create_index(op.f('ix_sensor_name'), 'sensor', ['name'], unique=False)
    op.create_index(op.f('ix_sensor_user_id'), 'sensor', ['user_id'], unique=False)
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('sensor_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_attribute'), 'data', ['attribute'], unique=False)
    op.create_index(op.f('ix_data_id'), 'data', ['id'], unique=True)
    op.create_index(op.f('ix_data_sensor_id'), 'data', ['sensor_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_sensor_id'), table_name='data')
    op.drop_index(op.f('ix_data_id'), table_name='data')
    op.drop_index(op.f('ix_data_attribute'), table_name='data')
    op.drop_table('data')
    op.drop_index(op.f('ix_sensor_user_id'), table_name='sensor')
    op.drop_index(op.f('ix_sensor_name'), table_name='sensor')
    op.drop_index(op.f('ix_sensor_id'), table_name='sensor')
    op.drop_table('sensor')
    op.drop_index(op.f('ix_user_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    ### end Alembic commands ###
